/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Cliente;

/**
 *
 * @author yuri duque ADM
 */
public class AlterarDadosCliente extends javax.swing.JFrame {

    /**
     * Creates new form AlterarDadosCliente
     */
    public AlterarDadosCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbutton_Criar = new javax.swing.JButton();
        jbutton_Cancelar = new javax.swing.JButton();
        Jrb_Juridica = new javax.swing.JRadioButton();
        Jrb_Fisica = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Jlb_TipoPessoa = new javax.swing.JLabel();
        Jlb_Nome = new javax.swing.JLabel();
        Jtf_Nome = new javax.swing.JTextField();
        Jlb_CPF = new javax.swing.JLabel();
        Jtf_CPF = new javax.swing.JTextField();
        Jlb_telefone = new javax.swing.JLabel();
        Jtf_telefone = new javax.swing.JTextField();
        Jlb_Endereco = new javax.swing.JLabel();
        Jlb_Estado = new javax.swing.JLabel();
        Jlb_Cidade = new javax.swing.JLabel();
        Jtf_Estado = new javax.swing.JTextField();
        Jtf_Cidade = new javax.swing.JTextField();
        Jlb_CEP = new javax.swing.JLabel();
        Jtf_CEP = new javax.swing.JTextField();
        Jlb_Logradouro = new javax.swing.JLabel();
        Jtf_Logradouro = new javax.swing.JTextField();
        Jlb_Bairo = new javax.swing.JLabel();
        Jtf_Bairo = new javax.swing.JTextField();
        Jlb_Numero = new javax.swing.JLabel();
        Jtf_Numero = new javax.swing.JTextField();
        Jlb_Complemento = new javax.swing.JLabel();
        Jtf_Complemento = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu_Logar = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CoelhoRapido2.png"))); // NOI18N
        jLabel1.setText("Coelho Rápido");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbutton_Criar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton_Criar.setText("Alterar");

        jbutton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutton_Cancelar.setText("Cancelar");

        Jrb_Juridica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jrb_Juridica.setText("Júridica");

        Jrb_Fisica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jrb_Fisica.setText("Física");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Alterar dados Cliente");

        Jlb_TipoPessoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_TipoPessoa.setText("Pessoa:");

        Jlb_Nome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Nome.setText("Nome:");

        Jlb_CPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_CPF.setText("CPF:");

        Jlb_telefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_telefone.setText("Telefone:");

        Jlb_Endereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Endereco.setText("Endereço:");

        Jlb_Estado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Estado.setText("Estado:");

        Jlb_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Cidade.setText("Cidade:");

        Jlb_CEP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_CEP.setText("CEP:");

        Jlb_Logradouro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Logradouro.setText("Logradouro:");

        Jlb_Bairo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Bairo.setText("Bairo:");

        Jlb_Numero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Numero.setText("Número:");

        Jlb_Complemento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Jlb_Complemento.setText("Complemento:");

        jmenu_Logar.setText("Logar");
        jMenuBar1.add(jmenu_Logar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbutton_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbutton_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlb_Nome)
                            .addComponent(Jlb_CPF))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jtf_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jlb_telefone)
                                .addGap(12, 12, 12)
                                .addComponent(Jtf_telefone))
                            .addComponent(Jtf_Nome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlb_Cidade)
                            .addComponent(Jlb_Estado))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jtf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jlb_CEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jtf_CEP))
                            .addComponent(Jtf_Cidade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlb_Logradouro)
                            .addComponent(Jlb_Bairo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(Jlb_Numero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jtf_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Jtf_Logradouro))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jlb_Complemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtf_Complemento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jtf_Bairo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jlb_TipoPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jrb_Juridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jrb_Fisica))
                            .addComponent(Jlb_Endereco))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jrb_Juridica)
                    .addComponent(Jrb_Fisica)
                    .addComponent(Jlb_TipoPessoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Nome)
                    .addComponent(Jtf_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_CPF)
                    .addComponent(Jtf_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlb_telefone)
                    .addComponent(Jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Jlb_Endereco)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Estado)
                    .addComponent(Jtf_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlb_CEP)
                    .addComponent(Jtf_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Cidade)
                    .addComponent(Jtf_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Logradouro)
                    .addComponent(Jtf_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Bairo)
                    .addComponent(Jtf_Bairo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlb_Numero)
                    .addComponent(Jtf_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlb_Complemento)
                    .addComponent(Jtf_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbutton_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbutton_Criar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarDadosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlb_Bairo;
    private javax.swing.JLabel Jlb_CEP;
    private javax.swing.JLabel Jlb_CPF;
    private javax.swing.JLabel Jlb_Cidade;
    private javax.swing.JLabel Jlb_Complemento;
    private javax.swing.JLabel Jlb_Endereco;
    private javax.swing.JLabel Jlb_Estado;
    private javax.swing.JLabel Jlb_Logradouro;
    private javax.swing.JLabel Jlb_Nome;
    private javax.swing.JLabel Jlb_Numero;
    private javax.swing.JLabel Jlb_TipoPessoa;
    private javax.swing.JLabel Jlb_telefone;
    private javax.swing.JRadioButton Jrb_Fisica;
    private javax.swing.JRadioButton Jrb_Juridica;
    private javax.swing.JTextField Jtf_Bairo;
    private javax.swing.JTextField Jtf_CEP;
    private javax.swing.JTextField Jtf_CPF;
    private javax.swing.JTextField Jtf_Cidade;
    private javax.swing.JTextField Jtf_Complemento;
    private javax.swing.JTextField Jtf_Estado;
    private javax.swing.JTextField Jtf_Logradouro;
    private javax.swing.JTextField Jtf_Nome;
    private javax.swing.JTextField Jtf_Numero;
    private javax.swing.JTextField Jtf_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbutton_Cancelar;
    private javax.swing.JButton jbutton_Criar;
    private javax.swing.JMenu jmenu_Logar;
    // End of variables declaration//GEN-END:variables
}
